<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <Compile Remove="Resources\**" />
        <EmbeddedResource Remove="Resources\**" />
        <None Remove="Resources\**" />
    </ItemGroup>
    <ItemGroup Condition="'$(Configuration)' != 'Debug'">
        <Compile Remove="Tests\**" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23.1">
            <Private>False</Private>
        </PackageReference>
        <PackageReference Include="VideoLan.LibVLC.Mac" Version="3.1.3.1">
            <Private>False</Private>
        </PackageReference>
        <PackageReference Include="LibVLCSharp" Version="3.10.0">
            <Private>False</Private>
        </PackageReference>
    </ItemGroup>
    <ItemGroup>
        <!-- All members in an assembly -->
        <Publicize Include="TeamSoda.Duckov.Core" IncludeVirtualMembers="false" />
        <Publicize Include="SodaLocalization" IncludeVirtualMembers="false" />
        <Publicize Include="TeamSoda.Duckov.Utilities" IncludeVirtualMembers="false" />
        <Publicize Include="Plugins" IncludeVirtualMembers="false" />
        <Publicize Include="ItemStatsSystem" IncludeVirtualMembers="false" />
        <Publicize Include="LibVLCSharp" IncludeVirtualMembers="false" />
        <DoNotPublicize Include="TeamSoda.Duckov.Core:Duckov.MiniGames.GamingConsole.OnGamingConsoleInteractChanged" />
        <DoNotPublicize Include="TeamSoda.Duckov.Core:Duckov.UI.ManagedUIElement.onClose" />
        <DoNotPublicize Include="TeamSoda.Duckov.Core:Duckov.UI.InventoryDisplay.onDisplayDoubleClicked" />
        <DoNotPublicize Include="TeamSoda.Duckov.Core:Duckov.UI.SlotDisplay.onSlotDisplayDoubleClicked" />
        <DoNotPublicize Include="TeamSoda.Duckov.Core:Duckov.UI.ItemUIUtilities.OnSelectionChanged" />
        <DoNotPublicize Include="TeamSoda.Duckov.Core:UIInputManager.OnCancel" />
        <DoNotPublicize Include="Plugins:InputIndicator.OnAfterRefresh" />
        <DoNotPublicize Include="ItemStatsSystem:ItemStatsSystem.Items.Slot.onSlotContentChanged" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\YoutubeExplode\YoutubeExplode\YoutubeExplode.csproj" />
    </ItemGroup>
</Project>
